### ISSUE TITLE
Keine Verbindung zum Botframework Emulator

### ISSUE THREAD

**Issue by sascha-schieferdecker** [GovBotIO/govbot-sdk#1]
Nach wie beschrieben erfolgter Installation mit aktueller node-stable wird jeglicher Verbindungsversuch mit folgender Fehlermeldung quittiert:

`Error: Request to 'http://localhost:56567/v3/botstate/emulator/conversations/75k9g3e4e6hi' failed: [502] cannotconnect
    at Request._callback (C:\development\www\govbot\node_modules\botbuilder\lib\bots\ChatConnector.js:537:46)
    at Request.self.callback (C:\development\www\govbot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\development\www\govbot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\development\www\govbot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
`

Die URL selbst ist aber eigentlich aufrufbar:

http://localhost:56567/v3/botstate/emulator/conversations/75k9g3e4e6hi

`{"data":null,"eTag":"*"}`

Bot Framework Emulator ist Version 3.5.31

**Comment by sascha-schieferdecker** [comment]
Kann geschlossen werden. Problem lag daran, dass bei der Verwendung eines Proxy in der .env explizit localhost ausgenommen werden muss. Vielleicht hilft es ja jemandem, so müsste die .env unter Verwendung eines Proxy aussehen:

`ENV=dev
PORT=3978
DEBUG_MODE=on
HTTP_PROXY=http://aaa.bb:8080
HTTPS_PROXY=http://aaa.bb:8080
NO_PROXY=localhost`

**Comment by chris0607** [comment]
Thank you for the information. We have added the lines to the file.
